// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSRcdKsSgfX-djJpRguWwaFtYk-a3MZz8',
    appId: '1:546158468883:web:e03feb0c1fb9a8c73044e6',
    messagingSenderId: '546158468883',
    projectId: 'medicine-time1',
    authDomain: 'medicine-time1.firebaseapp.com',
    storageBucket: 'medicine-time1.appspot.com',
    measurementId: 'G-8QQWKR4RLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJSRVKBaV91MLEKUCUH7o4j3SEbX0cI18',
    appId: '1:546158468883:android:4f88836d61f51ef73044e6',
    messagingSenderId: '546158468883',
    projectId: 'medicine-time1',
    storageBucket: 'medicine-time1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QMLCUxJ1mLnwQqd0BRLziI7TjRyH7n8',
    appId: '1:546158468883:ios:b57f81a44f9daf973044e6',
    messagingSenderId: '546158468883',
    projectId: 'medicine-time1',
    storageBucket: 'medicine-time1.appspot.com',
    iosClientId: '546158468883-rln8igm6t2gv7e2p6q0kg4670bbmqlsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2QMLCUxJ1mLnwQqd0BRLziI7TjRyH7n8',
    appId: '1:546158468883:ios:67a5b568bbcc464e3044e6',
    messagingSenderId: '546158468883',
    projectId: 'medicine-time1',
    storageBucket: 'medicine-time1.appspot.com',
    iosClientId: '546158468883-amad6tefjs8eicic2a6nvfiu1pgn5loj.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicineTime.RunnerTests',
  );
}
